# cookiecutter-__PLATAFORM__-__TEMPLATE_MODEL__-__LANGUAGE__

[cookiecutter](https://github.com/lopesivan/cookiecutter-__PLATAFORM__-__TEMPLATE_MODEL__-__LANGUAGE__) template for __PLATAFORM__ __TEMPLATE_MODEL__ using __LANGUAGE__.

## Requirements

- [cookiecutter](https://github.com/cookiecutter/cookiecutter)

## Usage

```
    local test:
    PYENV_VERSION=3.12.6 cookiecutter .

    remote test:
	PYENV_VERSION=3.12.6 cookiecutter gh:lopesivan/cookiecutter-__PLATAFORM__-__TEMPLATE_MODEL__-__LANGUAGE__
```


